theme = "hugo_theme_pickles"
baseurl = "https://aliceindataland.rbind.io/"
languageCode = "en-us"
Title = "Alice in Dataland"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Alice Milivinti 2018 powered by Hugo, Pickles"
custom_css = "/static/css/custom.css"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
#  twitter = "Your Twitter username"
  facebook = "alice.milivinti"
#  instagram = "Your Instagram username"
#  googleplus = "Your Google+ account URL" # https://plus.google.com/u/0/xxxxxx
  github = "alice1020"
#  gitlab = "Your GitLab username"
#  npm = "Your npm username"
#  codepen = "Your CodePen username"
#  dribbble = "Your Dribbble username"
#  fivehundredpx = "Your 500px username" # 500px
#  flickr = "Your Flickr username"
#  pinterest = "Your Pinterest username"
#  tumblr = "Your Tumblr username"
#  vimeo = "Your Vimeo username"
#  youtube = "Your YouTube username"
  linkedin = "alicemilivinti"
  # Disqus shortname
  disqus = "aliceindataland"
  # Google Analytics API key.
  ga_api_key = "UA-119389886-1"
  author = "Alice Milivinti"
  authorwebsite = "alicemilivinti.com"
  avatar = "/img/IMG_1422.JPG"
  contact = "mailto:a.lice.milivinti@gmail.com"
  bio = "I am not an expert in anything except eating gelato. I discovered Dataland following a white rabbit. I am originally form Valtellina (Italy), but temporarily adopted by the USA."
  # Short subtitle/tagline. This is displayed in the header.
#  subtitle = "Short subtitle"
  # Logo image. This is displayed ogp image.
#  logo = "/path/to/logo"
  favicon = "/img/favicon.png"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

#[[menu.main]]
#    identifier = "Work Projects"
#    name = "Work Projects"
#    url = "/workprojects"
#    weight = 3

#[[menu.main]]
#    parent = "theme"
#    name = "creating-a-new-theme"
#    url = "/posts/creating-a-new-theme"
#    weight = 1

#[[menu.main]]
#    parent = "theme"
#    name = "migrate-from-jekyll"
#    url = "/posts/migrate-from-jekyll"
#    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "Alice"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2018"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
